export const CREATE_NOTIFICATIONS = "CREATE_NOTIFICATIONS";
export const NOTIFICATIONS_ERROR = "NOTIFICATIONS_ERROR";
export const START_NOTIFICATIONS_RELOAD = "START_NOTIFICATIONS_RELOAD";
export const FINISHED_NOTIFICATIONS_RELOAD = "FINISHED_NOTIFICATIONS_RELOAD";
