export const READ_STATISTICS = "READ_STATISTICS";
export const STATISTICS_ERROR = "STATISTICS_ERROR";
export const START_STATISTICS_RELOAD = "START_STATISTICS_RELOAD";
export const FINISHED_STATISTICS_RELOAD = "FINISHED_STATISTICS_RELOAD";
